version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: dev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: blog
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports: ["3306:3306"]
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -pdevpass || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  phpmyadmin:
    image: phpmyadmin:5
    environment:
      PMA_HOST: db
      PMA_USER: dev
      PMA_PASSWORD: devpass
    ports: ["8081:80"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysqldata:
