version: "3.9"

networks:
  web: {}
  backend: {}

volumes:
  mysqldata: {}
  le_conf: {}      # <— declare the volumes used by edge/certbot
  le_webroot: {}

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      TZ: ${TZ:-America/Chicago}
      MYSQL_DATABASE: ${DB_NAME:?set_in_.env}
      MYSQL_USER: ${DB_USER:?set_in_.env}
      MYSQL_PASSWORD: ${DB_PASS:?set_in_.env}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:?set_in_.env}
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
      - --skip-name-resolve
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      backend:
        aliases: [ db-prod ]
    expose: [ "3306" ]
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p\"$MYSQL_ROOT_PASSWORD\" --silent" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      TZ: ${TZ:-America/Chicago}
      SPRING_PROFILES_ACTIVE: prod
      DB_USER: ${DB_USER:?set_in_.env}
      DB_PASS: ${DB_PASS:?set_in_.env}
      ADMIN_USER: ${ADMIN_USER:?set_in_.env}
      ADMIN_PASS: ${ADMIN_PASS:?set_in_.env}
      # (No SPRING_DATASOURCE_* here—now controlled by application-prod.properties)
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8080"
    networks: [backend]

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "3000"
    networks: [backend]

  edge:
    build:
      context: ../..
      dockerfile: infra/prod/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
    networks: [ web, backend ]
    volumes:
      - le_conf:/etc/letsencrypt
      - le_webroot:/var/www/certbot

  certbot:
    image: certbot/certbot:latest
    restart: "no"
    networks: [ web ]
    volumes:
      - le_conf:/etc/letsencrypt
      - le_webroot:/var/www/certbot
    entrypoint: sh
    command: -c "sleep infinity"


